# 애플리케이션 이름 (생략해도 문제 없어요)
spring.application.name=myapp

# 내장 톰캣 포트 변경이 필요하다면
server.port=8080

# 내장 톰캣 끄고 외장 톰캣 쓰고 싶으면 (외장 톰캣에 배포하고 싶을 때 활성화, aws에 톰캣이 별도로 있다면 주석 해제)
# spring.main.web-application-type=none

# 컨텍스트 패스 설정(디폴트는 "/" 즉 컨텍스트 패스가 없음)
server.servlet.context-path=/myapp

# jsp 쓰고 싶어요
# 프리릭스 값은 spring.mvc.view.prefix=/WEB-INF/ 만 사용하고 views 폴더를 없애는 경우도 많이 있음
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# jsp 수정하면 곧바로 반영하라!
server.servlet.jsp.init-parameters.development=true

# 커넥션 풀 설정
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.url=jdbc:log4jdbc:oracle:thin:@${ORACLE_IP}:${ORACLE_PORT}:xe
spring.datasource.username=${ORACLE_USER}
spring.datasource.password=${ORACLE_PASSWORD}
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.read-only=false

# 마이바티스
# mybatis.config-location=mybatis/config/mybatis-config.xml
mybatis.mapper-locations=mybatis/mapper/*.xml
mybatis.type-aliases-package=com.gdu.myapp.dto
mybatis.configuration.map-underscore-to-camel-case=true

# 구글 메일로 이메일 보내기
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.username=${EMAIL_USER}
spring.mail.password=${EMAIL_PASSWORD}

# 개별 파일 첨부 크기 10MB / 전체 파일 첨부 크기 100MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB

# 프록시 통해 WAS 접속한 실제 client ip 주소 알아낼 때 
server.forward-headers-strategy=native

# 인코딩
# server.servlet.encoding.charset=UTF-8
# server.servlet.encoding.enabled=true
# server.servlet.encoding.force=true

# 세션 유지 시간(초 단위)
server.servlet.session.timeout=1800

# 로그인을 처음 시도하면 http://localhost:8080/;jsessionid=F59911518B921DF62D09F0DF8F83F872 이렇게 URL에 자꾸 jsessionid 쿠키 값이 붙는다. 이거 방지.
# spring MVC 였다면 web.xml 파일에 <session-config><tracking-mode>COOKIE</tracking-mode></session-config> 태그
server.servlet.session.tracking-modes=cookie

# oracle timezone (aws에 oracle 11g 설치하고 올리려면 타임존이 안 맞는다고 오류가 발생)
spring.datasource.hikari.data-source-properties.oracle.jdbc.timezoneAsRegion=false